name: Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:    
  openwrt:
    name: OpenWrt Package - ${{ matrix.target.arch }}
    runs-on: ubuntu-latest
    needs: [ linux, linux-others ]
    environment: OpenWrt
    strategy:
      fail-fast: false
      matrix:
        target:
          - arch: "arm_cortex-a7"
            sdk: "https://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/openwrt-sdk-ipq40xx-generic_gcc-11.3.0_musl_eabi.Linux-x86_64.tar.xz"
    steps:
      - uses: actions/checkout@v2
      - name: Install build requirements
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
          gettext git java-propose-classpath libelf-dev libncurses5-dev \
          libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
          python3-distutils python3-setuptools python3-dev rsync subversion \
          swig time xsltproc zlib1g-dev
      - name: Install OpenWrt SDK
        run: |
          set -e
          wget -O openwrt-sdk.tar.xz ${{ matrix.target.sdk }}
          xz -q -d openwrt-sdk.tar.xz && tar -xvf openwrt-sdk.tar
          mv -f openwrt-sdk-* openwrt-sdk
      - name: Build Package
        run: |
          set -e
          echo "src-link aliyundrive $GITHUB_WORKSPACE/openwrt" > openwrt-sdk/feeds.conf
          echo 'CONFIG_PACKAGE_aliyundrive-webdav=y
          CONFIG_PACKAGE_luci-app-aliyundrive-webdav=y
          ' >> openwrt-sdk/.config
          cd openwrt-sdk
          cat feeds.conf.default >> feeds.conf
          cat feeds.conf

          ./scripts/feeds update -a > /dev/null
          make defconfig

          ./scripts/feeds install -d y -f -a
          make package/aliyundrive-webdav/compile V=s
          make package/luci-app-aliyundrive-webdav/compile V=s
          tree bin/packages/
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: aliyundrive-webdav-openwrt-${{ matrix.target.arch }}
          path: openwrt-sdk/bin/packages/*/aliyundrive/aliyundrive-webdav*.ipk
          if-no-files-found: error
      - name: Archive luci packages
        uses: actions/upload-artifact@v2
        if: ${{ matrix.target.arch == 'aarch64_generic' }}
        with:
          name: aliyundrive-webdav-openwrt-${{ matrix.target.arch }}
          path: openwrt-sdk/bin/packages/*/aliyundrive/luci-*.ipk
          if-no-files-found: error
      - name: Upload package to GitHub Release
        uses: softprops/action-gh-release@v1
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          files: |
            openwrt-sdk/bin/packages/*/aliyundrive/aliyundrive-webdav*.ipk
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          generate_release_notes: true
      - name: Upload luci packages to GitHub Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.target.arch == 'aarch64_generic' }}
        with:
          files: |
            openwrt-sdk/bin/packages/*/aliyundrive/luci-*.ipk
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          generate_release_notes: true
